### ISSUE TITLE
VFL Backdoor: poison_grad*0 in MNIST while poison_grad in NUSWIDE

### ISSUE THREAD

**Issue by AlphaPav** [FederatedAI/research#1]
Hi @jorghyq2016 @yankang18 

To update the server's model,  in the NUSWIDE dataset, poison_grad is used (poison_grad*10 in the function get_poisoned_matrix)

https://github.com/FederatedAI/research/blob/main/publications/vfl_backdoor/vfl_nuswide_backdoor.ipynb
![image](https://user-images.githubusercontent.com/32030872/132969491-0ccf4083-5e9c-4ad4-8950-ec575033c4bc.png)

However, in the MNIST dataset, poison_grad*0 is used. Why do you set the poisoned gradients to zero for the MNIST dataset? 
https://github.com/FederatedAI/research/blob/main/publications/vfl_backdoor/vfl_mnist_backdoor.ipynb 
![image](https://user-images.githubusercontent.com/32030872/132969547-2b2b755e-9612-4571-a85e-77643d27ff54.png)

I am wondering why do you use the zero gradients rather than the backdoor gradient in MNIST. 
Thank you in advance. Looking forward to hearing from you. 
Best,
Chulin

**Comment by AlphaPav** [comment]
Moreover, the following results for the MNIST can not be reproduced when 'amplify_rate =10' or  'amplify_rate =20'. 
![image](https://user-images.githubusercontent.com/32030872/132969601-5f347b08-f25a-4dc9-9fb5-54db0b5aac93.png)

In the released code where 'amplify_rate =10', the official result of backdoor accuracy is always zero for every epoch. 
![image](https://user-images.githubusercontent.com/32030872/132969624-2619a543-510d-44b2-950d-55e6ffee9338.png)


May I ask how to reproduce the results in your paper? @jorghyq2016  @yankang18 Did I miss anything?
Thanks.

**Comment by jorghyq2016** [comment]
Thanks for reporting these issues. 
For the first question, the function get_poisoned_matrix are used for both output replacement and  gradient replacent. Here in the forward pass, the amplify_rate is set to 0 so that the output of the target sample will be 0 (to fool the active party).  This should be the same for MNIST and NUSWIDE dataset. 
For the second  question, the problem is the amount of the poisond sample. There should be ~1% poisoned sample (as described in the paper) and in the previous code, this is set to ~0.1%, and therefore the results cannot be replicated. Sorry for this.
I have updated the code and fixed these two problems. If there's other problems , just let me know.
