### ISSUE TITLE
How to reproduce privacy analysis

### ISSUE THREAD

**Issue by zgzjdx** [FederatedAI/research#10]
Hi, thank you for the codebase!
I would like to know how to reproduce privacy analysis in FedCG paper (section 3.4 Privacy Analysis). I would appreciate it if you could give me some advice.

Best regards,
Yiqi Tong

**Comment by jorghyq2016** [comment]
The privacy analysis is based on the commonly used DLG attack (Deep Leakage from Gradients). 
There are three settings in FedCG paper:
1. FedAvg. The server has access to whole model (both structure and model weights). (naive DLG) 
2. FedSplit. The server only has access to the shared  top model (structure and weights). To reconstruct the raw data, it is assumed here the server also knows the model structure of the bottom model, but with random weights.  
3. FedCG. In addition to FedSplit, the server can get class-dependent feature vector from the generator. So the server can add an additional loss which encourages the output of the bottom model to match the outputs from the generator. In a simplified version, one can simply take the real intermediate outputs of the bottom model instead of the outputs from the generator.

Hope this could help. Best.

**Comment by zgzjdx** [comment]
Hi@jorghyq2016, thank you for your kind advice, it helps me a lot.
However, I still have a few more questions.
1. Should I conduct privacy analysis during the FedCG model training process (e.g., using DLG attacks in each round) or after training is completed？
2. How many images should I recovered from DLG to fairly reproduce the PSNR results in your paper (Table 2) and the ground truth images are randomly chosen from one client or directly chosen from all of the clients.

Thank you for your reponse, your paper is very clear and has taught me a lot as a newcomer to federated learning.
Looking forward to your reply.


Best regards,
Yiqi Tong

**Comment by jorghyq2016** [comment]
1) This can be done offline. You can either use a random initialized model or trained model, the results may differ a bit depending on the setting, but the trend is the same.
2) We randomgly select 10 images from each client (e.g. total 40 images if there are 4 clients).

Best.

**Comment by yankang18** [comment]
This issue was solved
